languageCode = "fr"
languageName = "French"
weight = 2
title = "Songtsen.org"

[params]
  displayName = "FR"
  isoCode = "fr"
  rtl = false
  dateFormat = "1er Janvier 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"
