# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

#[[main]]
#  name = "Blog"
#  pageRef = "posts"
#  weight = 10

[[main]]
  name = "Songtsen"
  pageRef = "songtsen"
  weight = 1

  [[main]]
    name = "About Songtsen"
    parent = "Songtsen"
    pageRef = "songtsen"
    weight = 1

  [[main]]
    name = "Founding teachers"
    parent = "Songtsen"
    pageRef = "songtsen/founding-teachers"
    weight = 2

  [[main]]
    name = "Spiritual Directors"
    parent = "Songtsen"
    pageRef = "songtsen/spiritual-directors"
    weight = 3


[[main]]
  name = "KRF Development"
  pageRef = "krf"
  weight = 2

  [[main]]
    name = "About KRF"
    parent = "KRF Development"
    pageRef = "krf"
    weight = 1

  [[main]]
    name = "Origins"
    parent = "KRF Development"
    pageRef = "krf/origins"
    weight = 2

  [[main]]
    name = "Objectives"
    parent = "KRF Development"
    pageRef = "krf/objectives"
    weight = 3

  [[main]]
    name = "Projects"
    parent = "KRF Development"
    pageRef = "krf/projects"
    weight = 4

  [[main]]
    name = "How to make a donation"
    parent = "KRF Development"
    pageRef = "krf/how-to-make-a-donation"
    weight = 5

[[main]]
  name = "Padmakara"
  pageRef = "padmakara"
  weight = 3

  [[main]]
    name = "About Padmakara"
    parent = "Padmakara"
    pageRef = "padmakara"
    weight = 1

  [[main]]
    name = "Activities"
    parent = "Padmakara"
    pageRef = "padmakara/activities"
    weight = 2

  [[main]]
    name = "Projects "
    parent = "Padmakara"
    pageRef = "padmakara/projects"
    weight = 3

  [[main]]
    name = "Resources"
    parent = "Padmakara"
    pageRef = "padmakara/resources"
    weight = 4

[[main]]
  name = "Chanteloube"
  pageRef = "chanteloube"
  weight = 4

  [[main]]
    name = "About chanteloube"
    parent = "Chanteloube"
    pageRef = "chanteloube"
    weight = 1

  [[main]]
    name = "The Chanteloube Stupas"
    parent = "Chanteloube"
    pageRef = "chanteloube/the-stupas"
    weight = 2

  [[main]]
    name = "Origins"
    parent = "Chanteloube"
    pageRef = "chanteloube/origins"
    weight = 3

  [[main]]
    name = "Activities"
    parent = "Chanteloube"
    pageRef = "chanteloube/activities"
    weight = 4

  [[main]]
    name = "Programs & Events"
    parent = "Chanteloube"
    pageRef = "chanteloube/events"
    weight = 5

  [[main]]
    name = "Practical details"
    parent = "Chanteloube"
    pageRef = "chanteloube/practical-details"
    weight = 6

  [[main]]
    name = "Become a member"
    parent = "Chanteloube"
    pageRef = "chanteloube/become-a-member"
    weight = 7

[[main]]
  name = "Siddhartha"
  pageRef = "siddhartha"
  weight = 5

    [[main]]
      name = "About Siddhartha"
      parent = "Siddhartha"
      pageRef = "siddhartha"
      weight = 1

    [[main]]
      name = "Our goals"
      parent = "Siddhartha"
      pageRef = "siddhartha/our-goals"
      weight = 2

    [[main]]
      name = "How Siddhartha helps"
      parent = "Siddhartha"
      pageRef = "siddhartha/how-siddhartha-helps"
      weight = 3

    [[main]]
      name = "How Siddhartha works"
      parent = "Siddhartha"
      pageRef = "siddhartha/how-siddhartha-works"
      weight = 4

    [[main]]
      name = "Projects"
      parent = "Siddhartha"
      pageRef = "siddhartha/projects"
      weight = 5


[[subnavigation]]
 name = "Events"
 pageRef = "chanteloube/events"
 weight = 10
[[subnavigation]]
 name = "How to get there"
 pageRef = "chanteloube/practical-details/how-to-get-there"
 weight = 20
[[subnavigation]]
 name = "On line bookshop"
 url = "https://www.padmakara.com"
 weight = 30
[[subnavigation]]
 name = "Newsletter"
 pageRef = "songtsen/newsletter"
 weight = 40
[[subnavigation]]
 name = "Contact"
 pageRef = "songtsen/contact"
 weight = 50



# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20
