# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

#[[main]]
#  name = "Blog"
#  pageRef = "posts"
#  weight = 10

[[main]]
  name = "Songtsen"
  pageRef = "songtsen"
  weight = 1

  [[main]]
    name = "About Songtsen"
    parent = "Songtsen"
    pageRef = "songtsen"
    weight = 1

  [[main]]
    name = "Founding teachers"
    parent = "Songtsen"
    pageRef = "songtsen/founding-teachers"
    weight = 2

  [[main]]
    name = "Spiritual Directors"
    parent = "Songtsen"
    pageRef = "songtsen/spiritual-directors"
    weight = 3


[[main]]
  name = "KRF Development"
  pageRef = "krf"
  weight = 2

  [[main]]
    name = "About KRF"
    parent = "KRF Development"
    pageRef = "krf"
    weight = 1

  [[main]]
    name = "Origins"
    parent = "KRF Development"
    pageRef = "krf/origins"
    weight = 2

  [[main]]
    name = "Objectives"
    parent = "KRF Development"
    pageRef = "krf/objectives"
    weight = 3

  [[main]]
    name = "Projects"
    parent = "KRF Development"
    pageRef = "krf/projects"
    weight = 4

  [[main]]
    name = "How to make a donation"
    parent = "KRF Development"
    pageRef = "krf/how-to-make-a-donation"
    weight = 5

[[main]]
  name = "Padmakara"
  pageRef = "padmakara"
  weight = 3

  [[main]]
    name = "About Padmakara"
    parent = "Padmakara"
    pageRef = "padmakara"
    weight = 1

  [[main]]
    name = "Activities"
    parent = "Padmakara"
    pageRef = "padmakara/activities"
    weight = 2

  [[main]]
    name = "Projects "
    parent = "Padmakara"
    pageRef = "padmakara/projects"
    weight = 3

  [[main]]
    name = "Resources"
    parent = "Padmakara"
    pageRef = "padmakara/resources"
    weight = 4

[[main]]
  name = "Chanteloube"
  pageRef = "chanteloube"
  weight = 4

[[main]]
  name = "Siddhartha"
  pageRef = "siddhartha"
  weight = 5

    [[main]]
      name = "About Siddhartha"
      parent = "Siddhartha"
      pageRef = "siddhartha/about-siddhartha"
      weight = 1

    [[main]]
      name = "Projects"
      parent = "Siddhartha"
      pageRef = "siddhartha/projects"
      weight = 2



#[[main]]
#  name = "Parent"
#  weight = 20

#[[main]]
#  name = "example sub-menu 1"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[main]]
#  name = "example sub-menu 2"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20

#[[main]]
#  name = "Categories"
#  pageRef = "categories"
#  weight = 20

#[[main]]
#  name = "Tags"
#  pageRef = "tags"
#  weight = 30


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20
